package stdlib

import "github.com/issueye/goscript/internal/module"

func init() {
	docs := map[string][]string{
		"@std/archive/zip": {
			"list(path)  列出 zip 文件中的条目",
			"extract(archivePath, dest)  解压 zip 文件到目标目录",
			"create(files, outPath)  按文件描述数组创建 zip 包",
		},
		"@std/buffer": {
			"from(value, encoding?) -> Buffer  从字符串、数组或 Buffer 创建 Buffer",
			"alloc(size, fill?) -> Buffer  创建指定长度的 Buffer，可选填充值",
			"byteLength(value, encoding?)  计算值编码后的字节长度",
			"concat(buffers) -> Buffer  合并 Buffer 数组",
			"isBuffer(value)  判断值是否为 Buffer",
			"buffer.length  Buffer 字节长度",
			"buffer.toString(encoding?)  按编码转成字符串",
			"buffer.toArray()  转成字节数字数组",
			"buffer.slice(start?, end?) -> Buffer  截取 Buffer",
		},
		"@std/compress/gzip": {
			"compress(value, options?) -> Buffer  gzip 压缩字符串或 Buffer",
			"decompress(value, options?)  gzip 解压，默认返回字符串",
			"compressFileSync(src, dst)  同步压缩文件",
			"decompressFileSync(src, dst)  同步解压文件",
		},
		"@std/cli": {
			"command(options?) -> cmd  创建 Cobra 风格命令对象，支持 use/short/long/aliases/run/preRun/postRun/args/version",
			"root(options?) -> cmd  command 的别名，用于创建根命令",
			"cmd.addCommand(...commands)  添加子命令",
			"cmd.command(options?) -> cmd  创建并添加子命令",
			"cmd.flags() -> flags  返回当前命令 flag 集",
			"cmd.persistentFlags() -> flags  返回可被子命令继承的 flag 集",
			"flags.string(name, shorthand?, default?, usage?)  定义字符串 flag",
			"flags.bool(name, shorthand?, default?, usage?)  定义布尔 flag",
			"flags.int(name, shorthand?, default?, usage?)  定义整数 flag",
			"flags.number(name, shorthand?, default?, usage?)  定义数字 flag",
			"cmd.execute(args?)  解析参数、匹配子命令并执行 run 回调",
			"cmd.flag(name)  读取解析后的 flag 值",
			"cmd.usage()  返回帮助文本",
			"cmd.help()  输出帮助文本",
			"cmd.commandPath()  返回命令路径",
			"noArgs()/arbitraryArgs()/exactArgs(n)/minArgs(n)/maxArgs(n)/rangeArgs(min, max)  参数数量校验器",
		},
		"@std/crypto": {
			"randomUUID()  生成 UUID v4",
			"sha1(value)  计算 SHA-1 十六进制摘要",
			"sha256(value)  计算 SHA-256 十六进制摘要",
			"sha512(value)  计算 SHA-512 十六进制摘要",
			"hmac(algorithm, key, value)  计算 HMAC 摘要，algorithm 支持 sha1/sha256/sha512",
			"pbkdf2(password, salt, iterations, keyLength, algorithm?, options?)  派生密钥",
			"randomBytes(size)  生成随机字节数组",
			"timingSafeEqual(left, right)  常量时间比较两个字节值",
		},
		"@std/db": {
			"drivers  支持的数据库驱动名列表",
			"open(driver, dsn) -> conn  打开数据库连接",
			"conn.exec(query, params?)  执行 SQL 并返回影响行数等结果",
			"conn.query(query, params?)  查询多行，返回对象数组",
			"conn.queryOne(query, params?)  查询单行，无结果返回 null",
			"conn.prepare(query) -> stmt  创建预编译语句",
			"conn.begin() -> tx  开启事务",
			"conn.setMaxOpenConns(count)  设置最大打开连接数",
			"conn.setMaxIdleConns(count)  设置最大空闲连接数",
			"conn.ping()  检查连接是否可用",
			"conn.close()  关闭数据库连接",
			"tx.exec(query, params?)  在事务内执行 SQL",
			"tx.query(query, params?)  在事务内查询多行",
			"tx.queryOne(query, params?)  在事务内查询单行",
			"tx.prepare(query) -> stmt  在事务内创建预编译语句",
			"tx.commit()  提交事务",
			"tx.rollback()  回滚事务",
			"stmt.exec(params?)  执行预编译语句",
			"stmt.query(params?)  查询预编译语句",
			"stmt.queryOne(params?)  查询预编译语句单行",
			"stmt.close()  关闭预编译语句",
		},
		"@std/encoding/base64": {
			"encode(value, options?)  Base64 编码",
			"decode(text, options?)  Base64 解码，options.asBuffer 可返回 Buffer",
			"encodeURL(value, options?)  URL 安全 Base64 编码",
			"decodeURL(text, options?)  URL 安全 Base64 解码",
		},
		"@std/encoding/csv": {
			"parse(text, options?)  解析 CSV 文本",
			"stringify(rows, options?)  将数组或对象行序列化为 CSV",
			"readFileSync(path, options?)  读取并解析 CSV 文件",
			"writeFileSync(path, rows, options?)  序列化并写入 CSV 文件",
			"options.header  是否使用首行表头",
			"options.comma/comment/fieldsPerRecord/trimLeadingSpace  CSV 解析写入选项",
		},
		"@std/encoding/hex": {
			"encode(value)  十六进制编码",
			"decode(text, options?)  十六进制解码，options.asBuffer 可返回 Buffer",
		},
		"@std/events": {
			"EventEmitter() -> emitter  创建事件发射器",
			"emitter.on(event, listener)  监听事件",
			"emitter.once(event, listener)  监听一次事件",
			"emitter.off(event, listener)  移除监听器",
			"emitter.emit(event, ...args)  触发事件",
			"emitter.listeners(event)  返回事件监听器数组",
			"emitter.listenerCount(event)  返回监听器数量",
			"emitter.removeAllListeners(event?)  移除全部或指定事件监听器",
		},
		"@std/exec": {
			"run(command, argsOrOptions?)  执行命令并返回 exitCode/stdout/stderr",
			"output(command, args?)  执行命令并返回 stdout 字符串",
			"combinedOutput(command, args?)  执行命令并返回 stdout+stderr",
			"start(command, args?) -> process  启动进程并返回控制对象",
			"spawn(command, args?, options?) -> process  启动进程并暴露 stdin/stdout/stderr",
			"command(command, args?) -> cmd  创建可配置命令对象",
			"process.write(data)  写入子进程 stdin",
			"process.writeln(data?)  写入一行到 stdin",
			"process.closeStdin()  关闭 stdin",
			"process.wait()  等待进程结束",
			"process.kill()  终止进程",
			"cmd.setDir(path)  设置工作目录",
			"cmd.setEnv(env)  设置环境变量对象",
			"cmd.run()/output()/combinedOutput()/start()  执行已配置命令",
		},
		"@std/fs": {
			"readFileSync(path)  读取文件文本",
			"readTextSync(path)  readFileSync 的文本别名",
			"writeFileSync(path, data)  写入文件",
			"writeTextSync(path, data)  writeFileSync 的文本别名",
			"appendFileSync(path, data)  追加写入文件",
			"appendTextSync(path, data)  appendFileSync 的文本别名",
			"writeFileAtomicSync(path, data)  原子写入文件",
			"existsSync(path)  判断路径是否存在",
			"readdirSync(path, options?)  读取目录条目",
			"walkSync(root, options?)  递归遍历目录",
			"globSync(pattern)  按 glob 模式匹配文件",
			"copyFileSync(from, to)  复制文件",
			"rmSync(path, options?)  删除文件或目录",
			"mkdtempSync(prefix)  创建临时目录",
			"realpathSync(path)  返回真实路径",
			"lstatSync(path)  返回路径状态",
			"mkdirSync(path, options?)  创建目录",
			"statSync(path)  返回文件状态",
			"renameSync(from, to)  重命名或移动",
			"unlinkSync(path)  删除文件",
		},
		"@std/hash": {
			"adler32(value)  计算 Adler-32 十六进制摘要",
			"crc32(value)  计算 CRC-32 十六进制摘要",
			"crc64(value)  计算 CRC-64 十六进制摘要",
			"fnv1a(value)  计算 FNV-1a 十六进制摘要",
			"adler32Number(value)  返回 Adler-32 数字",
			"crc32Number(value)  返回 CRC-32 数字",
		},
		"@std/highlight": {
			"terminal(code, options?)  轻量代码高亮，返回 lines/text/lang",
			"options.lang  语言：json/diff/shell/gs/js/toml",
			"options.width  按终端宽度换行",
			"options.color  是否输出 ANSI 颜色",
		},
		"@std/log": {
			"createFileLogger(path, options?) -> logger  创建文件日志器",
			"logger.debug(...values)  写入 debug 日志",
			"logger.info(...values)  写入 info 日志",
			"logger.warn(...values)  写入 warn 日志",
			"logger.error(...values)  写入 error 日志",
			"logger.log(...values)  写入 info 日志",
			"logger.close()  关闭日志文件",
		},
		"@std/markdown": {
			"parse(source)  解析 Markdown，返回 block/inline AST 和 diagnostics",
			"renderTerminal(source, options?)  渲染 Markdown 为终端行，支持 options.width",
			"createStream(options?)  创建流式 Markdown 预览器，支持 append/snapshot/finalize",
			"fromHTML(html, options?)  将基础 HTML 转为 Markdown，支持 baseUrl/includeLinks/maxChars",
			"Block: document/paragraph/heading/code/list/list_item/blockquote/hr",
			"Inline: text/strong/em/code/link/softbreak/hardbreak",
		},
		"@std/mail": {
			"parseAddress(address)  解析单个邮件地址",
			"parseAddressList(addresses)  解析邮件地址列表",
			"parseMessage(message)  解析邮件消息文本",
			"formatAddress(address)  格式化邮件地址",
			"formatAddressList(addresses)  格式化邮件地址列表",
			"parseDate(date)  解析邮件日期",
			"formatDate(time?)  格式化为邮件日期字符串",
			"getHeader(headers, name)  从邮件头对象读取字段",
		},
		"@std/mime": {
			"typeByExtension(extension)  根据扩展名返回 MIME 类型",
			"extensionByType(type)  根据 MIME 类型返回扩展名",
			"parseMediaType(value)  解析媒体类型和参数",
			"formatMediaType(type, params?)  格式化媒体类型",
		},
		"@std/net/http/client": {
			"get(urlOrOptions, options?)  发起 GET 请求",
			"post(urlOrOptions, body?, options?)  发起 POST 请求",
			"request(options)  发起通用 HTTP 请求",
			"fetch(options)  request 的别名",
			"stream(options)  发起请求并返回流式响应",
			"response.status/statusText/body/headers/ok/contentLength  HTTP 响应字段",
			"response.close()  关闭流式响应体",
		},
		"@std/net/http/server": {
			"createServer(handler?, port?) -> server  创建并启动 HTTP 服务器",
			"handler(req, res)  HTTP 请求处理函数",
			"server.close()  关闭服务器",
			"res.status(code)  设置状态码",
			"res.setHeader(name, value)  设置响应头",
			"res.send(body)  发送文本响应",
			"res.json(value)  发送 JSON 响应",
			"res.end(body?)  结束响应",
		},
		"@std/net/ip": {
			"parseIP(ip)  解析 IP 地址",
			"parseCIDR(cidr)  解析 CIDR 网段",
			"contains(cidr, ip)  判断网段是否包含 IP",
			"splitHostPort(address)  拆分 host:port",
			"joinHostPort(host, port)  拼接 host:port",
			"lookupHost(host)  DNS 查询主机地址",
		},
		"@std/net/socket/client": {
			"connect(host, port) -> socket  连接 TCP 服务",
			"dial(host, port) -> socket  connect 的别名",
			"socket.write(data)/send(data)  写入数据",
			"socket.read(size?)  读取文本数据",
			"socket.recv()  读取默认大小数据",
			"socket.close()  关闭连接",
			"socket.setDeadline(timeoutMs)  设置读写超时",
		},
		"@std/net/socket/server": {
			"listen(port, handler) -> server  监听 TCP 端口",
			"createServer(port, handler) -> server  listen 的别名",
			"handler(socket)  连接处理函数",
			"server.close()  关闭服务器",
		},
		"@std/net/ws/client": {
			"connect(url, options?) -> ws  连接 WebSocket",
			"ws.send(data)  发送数据",
			"ws.sendText(text)  发送文本",
			"ws.recv()  接收一条消息",
			"ws.close()  关闭连接",
		},
		"@std/net/ws/server": {
			"createServer(port, handler) -> server  创建 WebSocket 服务器",
			"upgrade(req) -> ws  将 HTTP 请求升级为 WebSocket",
			"handler(ws)  WebSocket 连接处理函数",
			"server.close()  关闭服务器",
		},
		"@std/os": {
			"platform  当前操作系统平台",
			"arch  当前 CPU 架构",
			"eol  当前平台换行符",
			"type()  返回操作系统类型",
			"release()  返回系统版本",
			"homedir()  返回用户主目录",
			"tmpdir()  返回临时目录",
			"hostname()  返回主机名",
			"cpus()  返回 CPU 信息数组",
			"userInfo()  返回当前用户信息",
		},
		"@std/path": {
			"join(...parts)  拼接路径",
			"resolve(...parts)  解析为绝对路径",
			"relative(from, to)  计算相对路径",
			"normalize(path)  规范化路径",
			"dirname(path)  返回目录名",
			"basename(path)  返回文件名",
			"extname(path)  返回扩展名",
			"isAbs(path)  判断是否绝对路径",
			"toSlash(path)  转为斜杠路径",
			"fromSlash(path)  转为平台路径",
			"matches(pattern, path)  glob 匹配",
			"parse(path)  拆分路径对象",
			"format(pathObject)  从路径对象格式化路径",
			"splitList(value)  拆分 PATH 列表",
			"sep/delimiter  平台路径分隔符",
		},
		"@std/process": {
			"argv  当前脚本参数数组",
			"argv0  进程启动名",
			"pid  当前进程 ID",
			"env  环境变量对象",
			"cwd()  返回当前工作目录",
			"chdir(path)  切换工作目录",
			"execPath()  返回可执行文件路径",
			"getenv(name, fallback?)  读取环境变量",
			"envObject()  返回环境变量对象",
			"uptime()  返回进程运行秒数",
			"hrtime(previous?)  返回高精度时间数组",
			"setenv(name, value)  设置环境变量",
			"unsetenv(name)  删除环境变量",
			"exit(code?)  退出进程",
			"version  GoScript 版本",
		},
		"@std/runtime": {
			"runScript(path, options?)  在独立 VM 中执行外部 GoScript 文件并返回 exports",
			"callScript(path, exportName, args?, options?)  执行外部脚本并调用指定导出函数",
			"runTool(path, input?, options?)  callScript(path, \"run\", [input], options) 的便捷封装",
			"options.cwd  动态脚本执行工作目录，默认继承当前进程 cwd",
			"options.argv  设置外部脚本 process.argv",
			"options.autoMain  runScript 后自动调用 main()",
		},
		"@std/pty": {
			"spawn(command, args?, options?) -> pty  启动伪终端进程",
			"open(command, args?, options?) -> pty  spawn 的别名",
			"pty.write(data)  写入伪终端",
			"pty.writeln(data?)  写入一行",
			"pty.read(size?)  读取字节数组",
			"pty.readText(size?, timeoutMs?)  读取文本；传 timeoutMs 时超时返回 null",
			"pty.readTextTimeout(size?, timeoutMs?)  带超时读取文本，超时返回 null",
			"pty.readLine()  读取一行文本",
			"pty.resize(cols, rows)  调整终端尺寸",
			"pty.wait()  等待进程结束",
			"pty.kill()  终止进程",
			"pty.close()  关闭伪终端",
		},
		"@std/schema": {
			"validate(schema, value)  校验值并返回结果对象",
			"assert(schema, value)  校验失败时抛出错误",
		},
		"@std/signal": {
			"supported()  返回支持的信号名",
			"wait(signalsOrOptions?, timeoutMs?)  等待信号",
			"notify(signalsOrOptions?) -> watcher  创建信号监听器",
			"send(pid, signal?)  向进程发送信号",
			"watcher.wait(timeoutMs?)  等待下一次信号",
			"watcher.stop()  停止监听",
			"SIGINT/SIGTERM/...  常用信号常量",
		},
		"@std/sse": {
			"reader(stream) -> reader  从文本流创建 SSE 读取器",
			"parse(text)  解析 SSE 文本块",
			"reader.next()  读取下一个 SSE 事件",
			"reader.readAll()  读取所有 SSE 事件",
		},
		"@std/stream": {
			"fromString(text) -> stream  从字符串创建可读流",
			"stream.read(size?)  读取字节数组",
			"stream.readText(size?)  读取文本",
			"stream.readLine()  读取一行",
			"stream.readAll()  读取剩余全部文本",
			"stream.close()  关闭流",
		},
		"@std/template": {
			"render(source, data?, options?)  渲染文本模板",
			"renderHTML(source, data?, options?)  渲染 HTML 模板并转义",
			"renderFileSync(path, data?, options?)  读取文件并渲染模板",
			"escapeHTML(value)  HTML 转义",
		},
		"@std/table": {
			"layout(rows, options?)  按终端宽度布局表格，返回 lines/widths",
			"options.width  表格总宽度",
			"options.minColWidth  最小列宽",
			"options.wrap  是否按列宽换行",
		},
		"@std/text": {
			"chars(value)  返回剥离 ANSI 后的可见字符数组",
			"runes(value)  chars 的别名",
			"width(value)  计算剥离 ANSI 后的终端显示宽度",
			"truncateWidth(value, width)  按终端显示宽度截断文本",
			"padRightWidth(value, width)  按终端显示宽度右侧补空格",
			"wrapWidth(value, width)  按终端显示宽度换行，返回行数组",
			"stripAnsi(value)  移除 ANSI escape 序列",
		},
		"@std/terminal": {
			"isTTY(fd?)  判断文件描述符是否终端",
			"size(fd?)  返回终端列数和行数",
			"capabilities()  返回 clearScrollback、alternateScreen、resizeEvents、virtualTerminal 等能力",
			"read(size?)  从终端读取文本",
			"write(text)  写入终端",
			"writeln(text?)  写入终端并换行",
			"setRawMode(enabled?)  设置终端 raw 模式",
			"start(options?) -> session  启动终端会话，支持 raw、bracketedPaste、mouse、alternateScreen、hideCursor、restoreOnExit、restoreOnError、resizeDebounceMs、onInput、onResize、onError",
			"onInput(fn)/offInput(fn)  注册或注销终端输入监听",
			"onResize(fn)/offResize(fn)  注册或注销终端尺寸变化监听",
			"session.write(text)/writeln(text?)  写入终端",
			"session.size()  返回终端列数和行数",
			"session.setRawMode(enabled)  切换会话 raw 模式",
			"session.restore()  恢复 raw、Bracketed Paste、鼠标、光标和备用屏等会话终端状态",
			"session.stop()  停止会话并恢复终端状态",
			"session.drainInput(maxMs?, idleMs?)  清理会话输入事件队列",
			"clear(options?)/session.clear(options?)  清理屏幕，可显式 scrollback:true 清滚动历史",
			"renderFrame(frame, options?)/session.renderFrame(frame, options?)  原子化清屏/定位/裁剪渲染帧，支持 rows、cols、clip、diff、full",
			"session.redraw(fn)  合并回调中的 screen.clear/moveTo/write 输出后一次写入",
			"hideCursor()/showCursor()  隐藏或显示光标",
			"clearScreen()/clearLine()/clearFromCursor()  清理终端内容",
			"moveTo(row, col)/moveBy(rows, cols)  移动光标",
			"setTitle(title)  设置终端标题",
			"style(text, options?)  返回 ANSI 样式文本，支持 bold/dim/underline/inverse/fg/bg/color",
			"hyperlink(label, url, options?)  生成 OSC 8 终端链接，禁用时降级为 label <url>",
			"enterAlternateScreen()/leaveAlternateScreen()  切换备用屏",
			"enableMouse()/disableMouse()  切换鼠标事件上报",
			"enableBracketedPaste()/disableBracketedPaste()  切换 Bracketed Paste",
		},
		"@std/tui": {
			"createApp({ init?, update?, view?, state? }) -> app  创建脚本侧 TUI 状态机",
			"app.dispatch(msg)  向状态机派发消息并返回最新 state",
			"app.render(size?)  调用 view(state, size) 并返回帧文本",
			"app.run(options?)  进入全屏事件循环，自动处理输入、resize、tick 和终端恢复",
			"app.stop()  请求停止正在运行的 TUI 应用并恢复终端",
			"app.state()  返回当前 state",
			"key(name, raw?) / text(value) / resize(cols, rows) / tick()  构造常用消息",
			"box(content, options?)  渲染带边框面板，支持 title/width/height/padding/border",
			"input({ title?, value?, cursor?, placeholder?, prompt?, width?, focused?, meta? })  渲染单行输入框",
			"row(parts...) / column(parts...) / pad(content, padding?)  组合多行文本布局",
			"statusBar({ left?, center?, right? }, width)  渲染单行状态栏",
			"style(text, options?)  返回 ANSI 样式文本，复用 @std/terminal.style",
			"width(value) / truncate(value, width) / stripAnsi(value)  显示宽度工具",
			"run options: raw/alternateScreen/hideCursor/mouse/bracketedPaste/diff/clip/full/tickMs/resizeDebounceMs",
		},
		"@std/time": {
			"now()  返回当前 Date",
			"nowMs()  返回当前毫秒时间戳",
			"unix(seconds, nanoseconds?)  从 Unix 秒创建 Date",
			"unixMs(ms)  从毫秒时间戳创建 Date",
			"parse(value, layout?, timezone?)  解析时间字符串",
			"format(time, layout?, timezone?)  格式化时间",
			"add(time, duration)  时间加 duration",
			"since(time)  返回距离指定时间的毫秒数",
			"until(time)  返回到指定时间的毫秒数",
			"parseDuration(duration)  解析 Go duration 字符串为毫秒",
			"duration(value, unit?)  构造毫秒 duration",
			"sleep(ms)  睡眠指定毫秒",
			"RFC3339/RFC1123/...  常用时间格式常量",
		},
		"@std/timers": {
			"setTimeout(fn, delayMs, ...args)  延迟执行函数",
			"clearTimeout(id)  取消 timeout",
			"setInterval(fn, delayMs, ...args)  周期执行函数",
			"clearInterval(id)  取消 interval",
			"queueMicrotask(fn)  排入微任务",
			"sleep(ms)  阻塞等待指定毫秒",
		},
		"@std/toml": {
			"parse(text)  解析 TOML 文本",
			"stringify(value)  序列化为 TOML 文本",
			"readFileSync(path)  读取并解析 TOML 文件",
			"writeFileSync(path, value)  序列化并写入 TOML 文件",
		},
		"@std/url": {
			"parse(url) -> URL  解析 URL 字符串",
			"format(urlObject)  格式化 URL 对象",
			"resolve(base, ref)  解析相对 URL",
			"pathToFileURL(path)  文件路径转 file URL",
			"fileURLToPath(url)  file URL 转文件路径",
			"URL(input, base?) -> URL  构造 URL 对象",
			"URLSearchParams(init?) -> params  构造查询参数对象",
			"url.toString()/toJSON()  返回 URL 字符串",
			"params.get(name)/has(name)  读取查询参数",
			"params.set(name, value)/append(name, value)  设置或追加查询参数",
			"params.delete(name)  删除查询参数",
			"params.toString()  序列化查询参数",
		},
		"@std/web":     webAPIDoc(),
		"@std/express": webAPIDoc(),
		"@std/xml": {
			"parse(text)  解析 XML 文本",
			"stringify(node)  序列化 XML 节点对象",
			"readFileSync(path)  读取并解析 XML 文件",
			"writeFileSync(path, node)  序列化并写入 XML 文件",
		},
		"@std/yaml": {
			"parse(text)  解析 YAML 文本",
			"stringify(value)  序列化为 YAML 文本",
			"readFileSync(path)  读取并解析 YAML 文件",
			"writeFileSync(path, value)  序列化并写入 YAML 文件",
		},
	}

	for path, signatures := range docs {
		module.RegisterNativeAPIDoc(path, signatures)
	}
}

func webAPIDoc() []string {
	return []string{
		"createApp() -> app  创建 Web 应用实例",
		"json() -> middleware  解析 JSON 请求体并写入 req.body",
		"text() -> middleware  将原始文本请求体写入 req.body",
		"static(root) -> middleware  从 root 目录提供静态文件服务",
		"proxy(targetOrOptions) -> middleware  代理请求到目标地址或代理配置",
		"forward(targetOrOptions) -> middleware  proxy 的别名，用于转发请求",
		"app.get(path, handler, ...handlers)  注册 GET 路由",
		"app.post(path, handler, ...handlers)  注册 POST 路由",
		"app.put(path, handler, ...handlers)  注册 PUT 路由",
		"app.patch(path, handler, ...handlers)  注册 PATCH 路由",
		"app.delete(path, handler, ...handlers)  注册 DELETE 路由",
		"app.all(path, handler, ...handlers)  注册匹配所有 HTTP 方法的路由",
		"app.use(handler, ...handlers)  注册全局中间件",
		"app.use(path, handler, ...handlers)  在指定路径前缀注册中间件",
		"app.listen(port?) -> server  监听端口并返回服务器对象；不传端口时使用随机端口",
		"server.close()  关闭服务器",
		"handler(req, res, next)  路由处理函数签名",
		"middleware(req, res, next)  中间件函数签名",
		"res.status(code)  设置响应状态码并返回 res",
		"res.setHeader(name, value)  设置响应头并返回 res",
		"res.send(body)  发送文本响应",
		"res.json(value)  发送 JSON 响应",
		"res.redirect(url)  使用默认状态码跳转到 URL",
		"res.redirect(status, url)  使用指定状态码跳转到 URL",
		"res.end(body?)  结束响应，可选发送响应体",
	}
}
